### ISSUE TITLE
builtin_types.h: No such file or directory

### ISSUE THREAD

**Issue by cirosantilli** [marwan-abdellah/GPU-Computing-SDK-4.2.9#1]
`Make` gives:

```
src/cutil.cpp:28:27: fatal error: builtin_types.h: No such file or directory
```

**Comment by marwan-abdellah** [comment]
That's a very old toolkit. I would recommend you to download the latest SDK.

**Comment by cirosantilli** [comment]
Yeah, I came here because this SDK had OpenCL examples, and I've read the new one does not. And I'd rather not install those SDKs, just clone a small repo and browse some samples.

**Comment by Tumb1eweed** [comment]
> Yeah, I came here because this SDK had OpenCL examples, and I've read the new one does not. And I'd rather not install those SDKs, just clone a small repo and browse some samples.

I came across the same problem when I try to build a conan package for nvcc, When I test nvcc, it reports :
fatal error: builtin_types.h: No such file or directory
[#include](https://forums.developer.nvidia.com/tag/include) “builtin_types.h”
^~~~~~~~~~~~~~~~~
Could you please show how to find this header file? In which library?
